# ===== FUENTE =====
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.5

# ===== VENTANA =====
confirm_os_window_close 0
enable_audio_bell no
window_padding_width 12
background_opacity 0.70
dynamic_background_opacity yes
hide_window_decorations yes

# ===== CURSOR =====
cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15

# ===== SCROLL =====
scrollback_lines 15000
wheel_scroll_multiplier 5.0

# ===== SELECCIÓN / PORTAPAPELES =====
copy_on_select yes
strip_trailing_spaces smart
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# ===== TABS =====
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{title}"

# ===== COLORES =====
foreground              #cdd6f4
background              #11111b
selection_foreground    #11111b
selection_background    #f5e0dc

cursor                  #f5e0dc
cursor_text_color       #11111b

active_border_color     #89b4fa
inactive_border_color   #45475a
bell_border_color       #f38ba8

active_tab_foreground   #11111b
active_tab_background   #89b4fa
inactive_tab_foreground #cdd6f4
inactive_tab_background #313244

color0  #45475a
color8  #585b70
color1  #f38ba8
color9  #f38ba8
color2  #a6e3a1
color10 #a6e3a1
color3  #f9e2af
color11 #f9e2af
color4  #89b4fa
color12 #89b4fa
color5  #f5c2e7
color13 #f5c2e7
color6  #94e2d5
color14 #94e2d5
color7  #bac2de
color15 #a6adc8

# ===== SHELL =====
shell_integration enabled

# ===== LIGADURAS / RENDIMIENTO =====
disable_ligatures never
repaint_delay 10
input_delay 3
sync_to_monitor yes

# ===== SHELL =====
shell /run/current-system/sw/bin/fish

# ===== SOFTWARE / RUTAS ÚTILES =====
editor /run/current-system/sw/bin/nvim
open_url_with /run/current-system/sw/bin/firefox
term xterm-kitty

# ===== INTEGRACIÓN =====
shell_integration enabled
allow_remote_control yes
listen_on unix:/tmp/kitty

# ===== SCROLL / RENDIMIENTO =====
scrollback_lines 15000
wheel_scroll_multiplier 5.0

# ===== MAPAS ÚTILES =====
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+w close_window
map ctrl+shift+q close_tab

